### ISSUE TITLE
Problem with unused library functions

### ISSUE THREAD

**Issue by hcvazquez** [unexpectedjs/unexpected-http#5]
My name is Hernan; with a group of colleagues we are conducting a research about unused code present in dependencies of JavaScript projects. We call this functions, UFF (Unused foreign functions). We found that in most projects there exist a great amount of UFF that are being included in the final bundle. 
 
In the case of unexpected-http (v 5.6.0) our tools detected approximately 1000 unused function in  dependencies. Removing those functions, the size of unexpected-http bundled could be reduced at least 60% (All tests passed).  I’m attaching the reduced version of your project. 
[unexpectedHttp(optimized).txt](https://github.com/unexpectedjs/unexpected-http/files/671170/unexpectedHttp.optimized.txt)

 
I’ll be very grateful if you can answer me the following questions:
-Did you were aware of the existence of these unused functions in your projects?
-Do you think that this is a problem? 
-Do you think that can be useful a tool for deal with this kind of problem?

Thanks in advance.

Cheers,

**Comment by alexjeffburke** [comment]
Hi there,

I understand that your research was a while back, but I'd like to respond.

I don't know exactly how your tools are measuring that because you didn't mention, but unexpected-http requires a number of other libraries and for use in browsers we produce a minified build that bundles a number of those dependencies exactly so that using it is possible with only a couple of script includes in an HTML file. There is no real alternative to that bundling if the library is to be usable.

This library is a testing tool and as such I'm not sure this is really a concern. The best place for removing anything that's unused from our dependencies, something like tree shaking within the build tool is likely the right place but this remains elusive and is not something that just works even with more modern build systems that browserify.

Thanks for the feedback.
